chanced/jsonptr

- src/error.rs
Use of the `std` feature currently fails to compile due to this typo.
> Fix typo in std:error::Error support

- src/pointer.rs
Hey!
When using `Pointer::push_back` with empty strings as keys the `count` was incremented, but the actual `inner` pointer value was not updated.
This PR fixes that.
I'm not sure why the check `!self.inner.ends_with('/')` was present in the first place.
> `Pointer::push_back`: Handle empty keys

- src/pointer.rs
Counterpart of #25 for `Pointer::pop_front`.
> `Pointer::pop_front`: Correctly handle empty strings

- CHANGELOG.md
- Cargo.toml
Also applied taplo for formatting.
> add asmello as an author

- CHANGELOG.md
- src/arbitrary.rs
- src/error.rs
- src/pointer.rs
- src/token.rs
- src/tokens.rs
This includes surprisingly few API changes. The main breaks come from the fact `Token` holds a (potentially non-static) lifetime now. I also remove several trait implementations and some methods, in favor of making the distinction between the encoded and decoded representations more explicit.
> Rework `Token` type

- src/error.rs
- src/index.rs
- src/lib.rs
- src/pointer.rs
- src/token.rs
Fixes #35 
As discussed in #35, this PR introduces a new type `Index` which encodes a parsed index from a `Token` type (or more generally, an RFC 6901-compliant string). 
This type is primarily useful to resolve the `-` token into a concrete numerical index given a known array length. It's also useful for reliably checking bounds against the provided length.
> introduce Index type for less error-prone index resolution

- src/pointer.rs
I missed this when first implementing the slice-like `Pointer` type. I _think_ the compiler will use the same layout as `str` regardless, but it's important to make sure. This assumption is needed for the unsafe code used in this type to be sound.
> add repr transparent to `Pointer`

- src/pointer.rs
This merges `is_valid` and `validate` so that the logic is not replicated.
@asmello we could make `Pointer::parse` into a `const fn` but it would mean accepting `&str`:
```rust
impl Pointer {
const fn new(s: &str) -> &Self {
unsafe { &*(core::ptr::from_ref::<str>(s) as *const Self) }
}
pub const fn parse(s: &str) -> Result<&Self, ParseError> {
match validate(s) {
Ok(_) => Ok(Self::new(s)),
Err(err) => Err(err),
}
}
}
```
> merge `is_valid` and `validate`

- LICENSE-APACHE
- LICENSE-MIT
- README.md
- src/index.rs
- src/lib.rs
- src/pointer.rs
- src/token.rs
- renames `PointerBuf::replace_token` to `replace`, `ReplaceTokenError` to `ReplaceError`
- changes `PointerBuf::push_back`, `PointerBuf::push_front`, `PointerBuf::replace` to accept `T: Into<Token>`
- implements `From` all integer types for `Token`
- cleans up and adds docs
> Small DX changes + more docs

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/assign.rs
- src/index.rs
- src/pointer.rs
- src/resolve.rs
- src/token.rs
In the process of migrating json-patch to version 0.5.1, I noticed one of their test cases was failing because we accept leading zeros and we shouldn't.
> Error on leading zeros when decoding indices

- CHANGELOG.md
- src/pointer.rs
solves #31 by adding fluid methods to `Pointer`:
- `with_leading_token` - prepends a token
- `with_trailing_token` - appends a token
- `with_appended` - appends a pointer
> Adds fluid methods to `Pointer`

- .github/workflows/check.yml
- CHANGELOG.md
- Cargo.toml
- src/pointer.rs
[See RFC](https://rust-lang.github.io/rfcs/2289-associated-type-bounds.html). This was stabilized in 1.79.0.
> use associated type bound

- CHANGELOG.md
- src/pointer.rs
- src/token.rs
Although a lot more inconvenient for us, some of our functions have invariants that have to be held externally, so they should be `unsafe fn`. This also makes it justifiable to expose them publicly (as then users can opt-in for manual checking of the invariants).
- Expose `Pointer::new` as a public (but unsafe) constructor (now called `Pointer::new_unchecked`). This gives users a way to bypass validation if they're sure they've got a valid string. Akin to `String::from_utf8_unchecked` and family.
- Add `PointerBuf::new_unchecked` as a new unsafe constructor, to match `Pointer::new_unchecked`.
- Made `Token::from_encoded_unchecked` unsafe. This one I didn't make public because I don't see much use for it. We may revisit this later.
> Refactor constructor safety

- CHANGELOG.md
- src/pointer.rs
> Add some box-related methods

- CHANGELOG.md
- src/pointer.rs
This is what it should've always been. It's technically a breaking change, but I think it's ok because most types that implement `AsRef<str>` would also implement `Into<String>`.
> update signature of PathBuf::parse

- CHANGELOG.md
- src/assign.rs
- src/index.rs
RFC 6901 is very strict about what it allows as an array index. Leading zeros are disallowed, and only digit characters are valid.
I had previously added a check for the leading zeros, but as it turns out that wasn't sufficient. Rust permits `+` as a prefix in a stringified `usize`, so we're currently more permissive than RFC 6901.
I think with this explicit check we finally reach exact parity with RFC 6901 in this aspect. `is_ascii_digit` is documented to check for the `U+0030 ‘0’ ..= U+0039 ‘9’.` range exactly, which is what we need.
This is a bug fix, though technically breaking.
> Stricter validation of RFC 6901 array indices

- CHANGELOG.md
- src/pointer.rs
Long due! These are quite useful.
I initially named them `is_suffix` and `is_prefix`, but it turns out that's confusing to read (which is the prefix/suffix of which?). So I went with the `std` choice for the `str` counterparts.
> Add `Pointer::starts_with` and `Pointer::ends_with`

- src/pointer.rs
- src/pointer/slice.rs
Quick follow-up of #84, because my naming sense was drunk.
This is _technically_ breaking since the trait is nameable, but it's sealed and we haven't released yet, so let's pretend the original name just never happened.
> rename SlicePointer --> PointerIndex

- .helix/languages.toml
I think anyone using Helix + rust-analyzer will want this set, otherwise clippy thinks there's a lot of unused code.
> add helix editor configuration

- CHANGELOG.md
- src/assign.rs
- src/diagnostic.rs
- src/index.rs
- src/token.rs
The `EncodingError` and `ParseIndexError` types are parsing errors with a
well defined 'subject', but they weren't previously made into `Diagnostic`
implementors, so they worked a bit inconsistently with other error types. This
PR makes it so those errors follow the same conventions and general structure
used by its kindred.
There is one related breaking change: `InvalidCharacterError` previously held
a copy of the subject, but in the new model this is a responsibility of its
enriched `Report<InvalidCharacterError>` type. Since some methods directly
depended on access to the subject, they had to be removed. I think this is
justifiable since the new error APIs are already breaking (we just should've
made this change in tandem with the other related breaks).
I don't have any other …
> migrate remaining errors to new model

- Cargo.lock
- Cargo.toml
This change makes `jsonptr` compatible with no-std environments when using the `json` feature flag.
> Bump versions and deny default features of serde crates
